<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="12" total="13" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="226" started-at="2019-07-24T02:25:37Z" finished-at="2019-07-24T02:25:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="226" started-at="2019-07-24T02:25:37Z" finished-at="2019-07-24T02:25:37Z">
      <class name="com.beagledata.hubble.hive2hubble.RewriteTestSql">
        <test-method status="FAIL" signature="testUseInsert_E_2()[pri:0, instance:com.beagledata.hubble.hive2hubble.RewriteTestSql@3701eaf6]" name="testUseInsert_E_2" duration-ms="209" started-at="2019-07-24T10:25:37Z" finished-at="2019-07-24T10:25:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [INSERT INTO HIVE.DB1.TEST SELECT * FROM TEST] but found [INSERT INTO DB1.TEST SELECT * FROM TEST]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [INSERT INTO HIVE.DB1.TEST SELECT * FROM TEST] but found [INSERT INTO DB1.TEST SELECT * FROM TEST]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.beagledata.hubble.hive2hubble.RewriteTestSql.testUseInsert_E_2(RewriteTestSql.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUseInsert_E_2 -->
      </class> <!-- com.beagledata.hubble.hive2hubble.RewriteTestSql -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
